name: "Tag: Release"

on:
  push:
    tags:
      - "v*.*.*.*"

permissions:
  contents: write

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get Tag Name
        id: tag_name
        shell: bash
        run: >-
          echo "::set-output name=TAG::$(echo ${{ github.ref }} | sed 's/refs\/tags\///' | sed 's/v//')"

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Restore Dependencies
        run: dotnet restore

      - name: Download Dalamud Library
        run: |
          wget https://goatcorp.github.io/dalamud-distrib/latest.zip -O /tmp/dalamud.zip
          unzip /tmp/dalamud.zip -d /tmp/dalamud

      - name: Build Plugin
        shell: bash
        run: |
          dotnet build --configuration Release --nologo -p:AssemblyVersion=${{ steps.tag_name.outputs.TAG }}
          sha512sum Travelcase/bin/x64/Release/Travelcase/latest.zip  >> checksums.txt
          cat checksums.txt
        env:
          DALAMUD_HOME: /tmp/dalamud
          IsCI: true

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          prerelease: false
          files: |
            Travelcase/bin/x64/Release/Travelcase/latest.zip
            checksums.txt
